version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daint123@
      POSTGRES_DB: srvls
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6400:6379"
    command: ["redis-server", "--requirepass", "daint123@"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: