apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvls-backend
  labels:
    app: srvls-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: srvls-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: srvls-backend
    spec:
      containers:
      - name: srvls-backend
        image: ${DOCKER_REGISTRY}/srvls-backend:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: srvls-db-credentials
              key: url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: srvls-db-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: srvls-db-credentials
              key: password
        - name: SPRING_REDIS_HOST
          value: "srvls-redis"
        - name: ELASTICSEARCH_HOST
          value: "srvls-elasticsearch"
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: srvls-aws-credentials
              key: access-key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: srvls-aws-credentials
              key: secret-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: srvls-jwt-secret
              key: secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: srvls-backend
  labels:
    app: srvls-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: srvls-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: srvls-backend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.srvls.example.com
    secretName: srvls-tls-cert
  rules:
  - host: api.srvls.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: srvls-backend
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: srvls-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: srvls-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
